### PR TITLE
Update for changed F@H psummary API.

### PR DESCRIPTION
**Pull request by jcoffland**
This is a fix for HFM so it will operate correctly with upcoming changes to the F@H API.

### CODE REVIEW

**Comment by harlam357** [comment]
Hi Joseph - Thank you for the PR and the heads up.  I see that this change hard codes 0.75 as the KFactor value, I assume because you guys are removing the "bonus" value from the json, as well as the "title" value.  I see in many cases already the "bonus" value is already zero and "title" empty.

Looking at all the KFactor values I have in my local project information, which has a lot of history beyond what is available via the json, all the KFactor values that are not zero are 0.75.

Is 0.75 now a universal standard?  And does this mean all projects are, without a doubt, enrolled in bonus calculation?

**Comment by jcoffland** [comment]
Yes.  You've got it exactly right.

**Comment by harlam357** [comment]
Thanks for the confirmation.

**Comment by jcoffland** [comment]
No problem.

**Pull request merged**
